/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LandRouteImport } from './routes/land'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RentRouteImport } from './routes/rent'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminViewingsRouteImport } from './routes/admin.viewings'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as SpecialistsIndexRouteImport } from './routes/specialists.index'
import { Route as SpecialistsSlugRouteImport } from './routes/specialists.$slug'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin.properties.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViewingsRoute = AdminViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => AdminRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsIndexRoute = SpecialistsIndexRouteImport.update({
  id: '/specialists/',
  path: '/specialists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsSlugRoute = SpecialistsSlugRouteImport.update({
  id: '/specialists/$slug',
  path: '/specialists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/land': typeof LandRoute
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/viewings': typeof AdminViewingsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/specialists/$slug': typeof SpecialistsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/specialists/': typeof SpecialistsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/land': typeof LandRoute
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/viewings': typeof AdminViewingsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/specialists/$slug': typeof SpecialistsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/specialists': typeof SpecialistsIndexRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/land': typeof LandRoute
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/viewings': typeof AdminViewingsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/specialists/$slug': typeof SpecialistsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/specialists/': typeof SpecialistsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/favorites'
    | '/land'
    | '/login'
    | '/rent'
    | '/admin/enquiries'
    | '/admin/viewings'
    | '/insights/$slug'
    | '/locations/$slug'
    | '/properties/$slug'
    | '/specialists/$slug'
    | '/admin/'
    | '/insights/'
    | '/locations/'
    | '/properties/'
    | '/specialists/'
    | '/admin/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/favorites'
    | '/land'
    | '/login'
    | '/rent'
    | '/admin/enquiries'
    | '/admin/viewings'
    | '/insights/$slug'
    | '/locations/$slug'
    | '/properties/$slug'
    | '/specialists/$slug'
    | '/admin'
    | '/insights'
    | '/locations'
    | '/properties'
    | '/specialists'
    | '/admin/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/favorites'
    | '/land'
    | '/login'
    | '/rent'
    | '/admin/enquiries'
    | '/admin/viewings'
    | '/insights/$slug'
    | '/locations/$slug'
    | '/properties/$slug'
    | '/specialists/$slug'
    | '/admin/'
    | '/insights/'
    | '/locations/'
    | '/properties/'
    | '/specialists/'
    | '/admin/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuyRoute: typeof BuyRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  LandRoute: typeof LandRoute
  LoginRoute: typeof LoginRoute
  RentRoute: typeof RentRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  SpecialistsSlugRoute: typeof SpecialistsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  SpecialistsIndexRoute: typeof SpecialistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viewings': {
      id: '/admin/viewings'
      path: '/viewings'
      fullPath: '/admin/viewings'
      preLoaderRoute: typeof AdminViewingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/': {
      id: '/specialists/'
      path: '/specialists'
      fullPath: '/specialists/'
      preLoaderRoute: typeof SpecialistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/$slug': {
      id: '/specialists/$slug'
      path: '/specialists/$slug'
      fullPath: '/specialists/$slug'
      preLoaderRoute: typeof SpecialistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminViewingsRoute: typeof AdminViewingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminViewingsRoute: AdminViewingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BuyRoute: BuyRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  LandRoute: LandRoute,
  LoginRoute: LoginRoute,
  RentRoute: RentRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  SpecialistsSlugRoute: SpecialistsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  SpecialistsIndexRoute: SpecialistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
